# Generated by Django 2.2 on 2020-08-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('material_spec', models.CharField(max_length=100, verbose_name='产品规格')),
                ('material_type', models.CharField(max_length=100, verbose_name='产品类型（采购产品、中间产品、最终产品）')),
                ('material_unit', models.CharField(max_length=10, verbose_name='产品单位')),
                ('material_num', models.IntegerField(verbose_name='数量')),
                ('material_price', models.FloatField(verbose_name='单价')),
                ('material_date', models.DateField(verbose_name='交货日期')),
                ('material_expl', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='MaterialRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_pos', models.SmallIntegerField(verbose_name='产品层次')),
                ('mat_num', models.IntegerField(verbose_name='组成上层产品的数量')),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_mat', to='material.Material', verbose_name='产品')),
                ('mat_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mat', to='material.Material', verbose_name='上层产品')),
                ('mat_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_mat', to='material.Material', verbose_name='最终产品')),
            ],
            options={
                'verbose_name': '产品关系',
                'verbose_name_plural': '产品关系',
            },
        ),
    ]
