# Generated by Django 2.2 on 2020-08-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_type',
        ),
    ]
