# Generated by Django 2.2 on 2020-08-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='alredy_cleared',
            field=models.FloatField(default=0, verbose_name='已付款金额'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='clear',
            field=models.BooleanField(default=False, verbose_name='是否已付全款'),
        ),
    ]
