# Generated by Django 2.2 on 2020-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0002_auto_20200809_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': '应收账款', 'verbose_name_plural': '应收账款'},
        ),
        migrations.AlterField(
            model_name='debt',
            name='alredy_cleared',
            field=models.FloatField(default=0, verbose_name='已收款金额'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='clear',
            field=models.BooleanField(default=False, verbose_name='是否全部回款'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='last_date',
            field=models.DateField(verbose_name='应收日期'),
        ),
    ]
