# Generated by Django 2.2 on 2020-08-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('comp_addr', models.CharField(max_length=200, verbose_name='公司地址')),
                ('comp_legal_person', models.CharField(max_length=100, verbose_name='法定代表人')),
                ('comp_agent_person', models.CharField(max_length=100, verbose_name='委托代理人')),
                ('comp_phone', models.CharField(max_length=20, verbose_name='电话')),
                ('comp_mail', models.CharField(max_length=20, verbose_name='邮编')),
                ('comp_bank_name', models.CharField(max_length=30, verbose_name='开户银行')),
                ('comp_bank_account', models.CharField(max_length=30, verbose_name='银行账号')),
                ('comp_tax_account', models.CharField(max_length=30, verbose_name='税号')),
                ('comp_contact_person', models.CharField(max_length=30, verbose_name='联系人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_place', models.CharField(max_length=200, verbose_name='合同签订地点')),
                ('order_code', models.CharField(max_length=200, verbose_name='甲方合同编号')),
                ('order_date', models.DateField(verbose_name='合同签订日期')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_buyer', to='order.Company', verbose_name='甲方')),
                ('mat_set', models.ManyToManyField(related_name='mat_order', to='material.Material', verbose_name='产品列表')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_seller', to='order.Company', verbose_name='乙方')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
