# Generated by Django 2.2 on 2020-08-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_addr',
            field=models.CharField(blank=True, max_length=200, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_agent_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='委托代理人'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_bank_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='银行账号'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_bank_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='开户银行'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_contact_person',
            field=models.CharField(blank=True, max_length=30, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_legal_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='法定代表人'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_mail',
            field=models.CharField(blank=True, max_length=20, verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_tax_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='税号'),
        ),
    ]
