# Generated by Django 2.2 on 2020-08-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200804_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_percent',
            field=models.FloatField(default=0.0, verbose_name='预付定金比例'),
        ),
    ]
