# Generated by Django 2.2 on 2020-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_deposit_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deposit_percent',
            field=models.FloatField(default=0.0, verbose_name='预付定金比例（百分数）'),
        ),
    ]
